### ISSUE TITLE
images for readme

### ISSUE THREAD

**Issue by chasemc67** [chasemc67/Mathematical_Functions_Reinforcement_Learning#1]
<img width="885" alt="screen shot 2018-05-13 at 8 09 20 pm" src="https://user-images.githubusercontent.com/6922982/39976621-9e4598a4-56e9-11e8-9360-cfba7a5a5a96.png">
<img width="640" alt="screen shot 2018-05-13 at 8 11 03 pm" src="https://user-images.githubusercontent.com/6922982/39976667-ceb378da-56e9-11e8-8521-e040edb6ec5d.png">

**Comment by MandyMeindersma** [comment]
?!?!?!?!!? friendo
